### ISSUE TITLE
نشر تفريغ على PyPI

### ISSUE THREAD

**Issue by AliOsm** [ieasybooks/tafrigh#17]

**Comment by awadammar** [comment]
Unfortunately, PyPI new user and new project registrations are temporarily suspended, therefore I think we have to wait for a while.
![image](https://github.com/ieasybooks/tafrigh/assets/31369634/6e223e29-b1be-45dd-9d08-8404702c952d)

**Comment by AliOsm** [comment]
Interesting, keep us updated please.

**Comment by AliOsm** [comment]
تم النشر: https://pypi.org/project/tafrigh.
