### ISSUE TITLE
التفريغ بنموذج ويسبر لا يعمل منذ 05-01-2024

### ISSUE THREAD

**Issue by GenoXu** [ieasybooks/tafrigh#40]
السلام عليكم ورحمة الله

بعد تثبيت لوازم البيئة، يظهر هذا التحذير:

![image](https://github.com/ieasybooks/tafrigh/assets/31614025/3b09d99b-ecb2-45a3-bc19-0a0f3672dfbb)

ثم تبقى المعالجة جارية لكن لا تقدَّم أي نتائج (انتظرت أكثر من ثلث ساعة على تفريغ مقطع مدته 10 دقائق لكن بلا فائدة)

**Comment by AliOsm** [comment]
سأبحث في المشكلة بإذن الله

**Comment by GenoXu** [comment]
جربت [خدمة تفريغ أخرى فصادفتني نفس المشكلة

![image](https://github.com/ieasybooks/tafrigh/assets/31614025/480e6a6b-e25d-4cf2-8be9-dd04a5db6335)
 
الظاهر أن المشكلة عامة

**Comment by AliOsm** [comment]
تم حل المشكلة على Colab، هل يمكنك المحاولة والتأكيد؟

**Comment by GenoXu** [comment]
![image](https://github.com/ieasybooks/tafrigh/assets/31614025/decddd3d-567e-486c-ba23-29474b65ebdd)

كتب الله أجركم
